home/urls.py
from django.urls import path, include
from .views import index, list

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('list/', list, name='list'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import index, list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('home.urls', namespace='list')),
]

home/models.py
from django.db import models

class Users(models.Model):
    name = models.CharField('Ім\'я', max_length=50)
    # email = models.CharField('Почта', max_length=150)

    class Meta:
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.name

home/forms.py
from .models import Users
from django.forms import ModelForm, TextInput

class UsersForm(ModelForm):
    class Meta:
        model = Users
        fields = ['name']

        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Поле для введення'
            })
        }

home/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import Users
from .forms import UsersForm
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    result = ''
    if request.method == 'POST':
        form = UsersForm(data=request.POST)
        if form.is_valid():
            name = request.POST['name']
            try:
                if Users.objects.get(name=name):
                    result = 'Вже бачилися, ' + name
            except ObjectDoesNotExist:
                form.save()
                result = 'Привіт, ' + name
            except Exception:
                result = 'Сталася помилка'

    form = UsersForm()

    context = {
        'form': form,
        'result': result,
    }
    return render(request, 'home/index.html', context)

def list(request):

    context = {
        'user': Users.objects.order_by('id'),
    }
    return render(request, 'home/list.html', context)

home/templates/home/index.html
<!--{% load static %}-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
    <!-- <link href="{% static 'css/customs.css' %}" rel="stylesheet"> -->
    <title>Home</title>
</head>
<body>
    <div class="mx-auto" style="width:500px; margin-top:25px">
            <h4 style="text-align:center; margin-bottom:20px">Введіть ваше Ім'я або Пошту:</h4>
            <form method="post">
                {% csrf_token %}
                {{ form.name }}<br>
                <button class="btn btn-success" type="sumbit" style="width:247px; height:40px">Привітатись</button>
                <a href="{% url 'home:list' %}" class="btn btn-primary" role="button" style="width:247px;height:40px">Посмотреть
                    спискок</a><br>
                <h5 style="margin-top:20px">Результат: {{result}}</h5>
            </form>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/list.html
<!--{% load static %}-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
    <!--<link href="{% static 'css/customs.css' %}" rel="stylesheet">-->
    <title>List</title>
</head>
<body>
    <div class="mx-auto" style="width:500px; margin-top:25px">
        <h4 style="text-align:center; margin-bottom:20px">Список усіх з ким привіталися:</h4>
            <ul class="list-group">
                {% if user %}
                    {% for i in user %}
                        <li class="list-group-item">
                            {{i.name}}
                        </li>
                    {% endfor %}
                {% else %}
                    <p>У вас нет записей!</p>
                {% endif %}
            </ul>
        <a href="{% url 'home:index' %}" class="btn btn-primary" role="button"
           style="width:500px; height:40px; margin-top:20px">Назад</a>
    </div>
</body>
</html>